# Generated by Django 5.0.14 on 2025-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='declaracao_regularidade_conformidade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
