# Generated by Django 5.0.14 on 2025-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instituicao_declaracao_regularidade_conformidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='declaracao_regularidade_conformidade',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='assinatura_solicitante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instituicoes/assinaturas/', verbose_name='Assinatura do Solicitante (PDF)'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='ata_eleicao_dirigente_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instituicoes/atas_eleicao/', verbose_name='Ata de Eleição do Quadro Dirigente (PDF)'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='comprovante_endereco_entidade_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instituicoes/comprovantes_endereco/', verbose_name='Comprovante de Endereço da Entidade (PDF)'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='declaracao_regularidade_conformidade_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instituicoes/declaracoes_regularidade/', verbose_name='Declaração de Regularidade e Conformidade (PDF)'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='estatuto_registrado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instituicoes/estatutos/', verbose_name='Estatuto Registrado e Alterações (PDF)'),
        ),
    ]
