# Generated by Django 5.0.14 on 2025-06-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_instituicao_declaracao_regularidade_conformidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='fabricante_do_componente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo_do_componente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_do_componente',
            field=models.CharField(default='Outros', max_length=50),
        ),
    ]
